// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzbwgmjdjdklflnbadxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6YndnbWpkamRrbGZsbmJhZHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTg5MDksImV4cCI6MjA2ODc3NDkwOX0.N7IED3OCxBmm156zvRUpFTUzLoqjjcJ1k5F3Q8Ma7aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});